# Generated by Django 4.2.6 on 2023-10-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Chips/Snacks', 'Chips/Snacks'), ('Beverages', 'Beverages'), ('Instant Noodles', 'Instant Noodles'), ('Healthcare', 'Healthcare'), ('Pantry Items', 'Pantry Items')], max_length=20, null=True)),
                ('quantity', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
