# Generated by Django 4.2.6 on 2023-11-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Chips/Snacks', 'Chips/Snacks'), ('Beverages', 'Beverages'), ('Instant Noodles', 'Instant Noodles'), ('Healthcare', 'Healthcare'), ('Pantry Items', 'Pantry Items')], max_length=20, null=True)),
                ('quantity', models.PositiveBigIntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Grocery',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
