# Generated by Django 4.2.6 on 2023-11-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_grocery_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='islow',
            field=models.BooleanField(default=False),
        ),
    ]
